---
- name: Deploy SSH key
  hosts: all
  become: yes
  tasks:
    - name: create a file
      file:
        path: /home/{{ ansible_user }}/.ssh/newfile
        state: touch
        mode: 0700
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: echo into file
      lineinfile:
        path: /home/{{ ansible_user }}/.ssh/newfile
        line: "{{ ssh_key }}"
        state: present
        mode: 0600
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: allow ssh key with ssh-copy-id
      shell: ssh-copy-id -i /home/{{ ansible_user }}/.ssh/newfile -o 'IdentityFile /home/{{ansible_user}}/.ssh/cloudmatePv' {{ ansible_user }}@{{ IP }}
      args:
        creates: /home/{{ ansible_user }}/.ssh/authorized_keys
