---
- name: Deploy SSH key
  hosts: localhost
  become: true
  tasks:
    - name: create a file
      file:
        path: /home/{{ ansible_user }}/.ssh/newfile.pub
        state: touch
        mode: 0600
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become: yes

    - name: echo into file
      lineinfile:
        path: /home/{{ ansible_user }}/.ssh/newfile.pub
        line: "{{ ssh_key }}"
        state: present
        mode: 0600
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: allow ssh key with ssh-copy-id
      command: ssh-copy-id -f -i /home/{{ ansible_user }}/.ssh/newfile.pub -o 'IdentityFile /home/{{ansible_user}}/.ssh/cloudmatePv' {{ ansible_user }}@{{ IP }}
