---
- name: Deploy SSH key
  hosts: all
  become: yes
  tasks:
    - name: Vérifier si le dossier .ssh existe
      stat:
        path: "~/.ssh"
      register: ssh_dir
    - name: Ajouter la clé publique dans le fichier authorized_keys
      lineinfile:
        path: "~/.ssh/authorized_keys"
        line: "{{ ssh_key }}"
        create: true
        insertafter: EOF
      when: ssh_dir.stat.exists
