---
- name: Deploy SSH key
  hosts: all
  become: yes
  tasks:
    - name: Copy SSH key from vars
      copy:
        content: "{{ ssh_key }}"
        dest: /home/{{ ansible_user }}/.ssh/
        mode: 0600
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"